links:
- text: 'top'
  href: '/?page=top'
- text: '開発日誌（ブログ）'
  href: '/?post'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: '旧bashcms'
    href: 'http:////test.usptomo.com/'
  - text: '作者ブログ'
    href: 'https:////b.ueda.tech/'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https:////twitter.com/ryuichiueda'
- icon: 'fa-youtube-square'
  href: 'https:////www.youtube.com/user/ryuichiueda/videos'
- icon: 'fa-github-square'
  href: 'https:////github.com/ryuichiueda'
- icon: 'fa-graduation-cap'
  href: 'https:////www.researchgate.net/profile/Ryuichi_Ueda'
hatena: '@'
pocket: '@'
twitter: 'ryuichiueda'
